### ISSUE TITLE
Configure HD quality

### ISSUE THREAD

**Issue by tillkruss** [hjdhjd/homebridge-unifi-protect2#32]
Hi, love your plugin and the fantastic rewrite. Maybe consider adding a GitHub Sponsor link 👍🏻

I've got G3 Flex cameras and the streams are all in `1280x720`:
```
[8/5/2020, 8:18:49 AM] [UniFi Protect] Driveway: Starting video stream: 1280x720, 30 fps, 299 kbps.
```

How can I change that to the `1920x1080` that the camera supports? For the stream mostly, but ideally also for the snapshots.

I've tried this:

```json
{
    "platform": "UniFi Protect",
    "debug": false,
    "controllers": [],
    "options": [
        "Enable.StreamOnly.High"
    ]
}
```

**Comment by brianmedia** [comment]
@tillkruss 
I have 3 G3 Flex cameras and they will stream in 1920 if requested from specific devices, but on iPhone i can only get 1280

(**iPad**) [8/5/2020, 10:28:15 AM] [UniFi Protect] Front: Starting video stream: 1920x1080, 30 fps, 802 kbps.
[8/5/2020, 10:28:38 AM] [UniFi Protect] Front: Stopped video stream.
(**iPhone**)[8/5/2020, 10:29:08 AM] [UniFi Protect] Front: Starting video stream: 1280x720, 30 fps, 299 kbps.

I've also tried disabling Med, Low... and also Enable ONLY High... but iphone always pulls Medium. See other long thread, which a bug has been found.. could be part of larger bug.

**Comment by hjdhjd** [comment]
@tillkruss You configured the plugin correctly. Snapshot **quality** is not really controlled by the plugin, but by HomeKit. It requests a snapshot size depending on what device type (say an iPhone versus an iPad Pro). It's working as designed.

@brianmedia This is not a bug. It's working as designed. Your issue is with the stream quality **HomeKit** is requesting. :smile:

It's also why I prioritize a medium-quality stream when configuring this plugin with G4 Pros by default (which are some of the cameras I have in my almost 20 camera setup!).

**Comment by tillkruss** [comment]
@hjdhjd: Is there a way to force snapshot and stream quality, ignoring what HomeKit requests?

**Comment by brianmedia** [comment]
@hjdhjd 
He specifically states his "streams" are only 1280x720. 
>I've got G3 Flex cameras and the streams are all in 1280x720

I was just stating the G3 Flex CAN stream 1920x1080, as i have 3 of them streaming in High. But it depends on what device HomeKit is on as to what stream quality it's choosing.

What is the logic as to what stream quality Homekit chooses?

**Comment by hjdhjd** [comment]
See https://github.com/hjdhjd/homebridge-unifi-protect2/issues/29#issuecomment-669347787
