### ISSUE TITLE
Multiple Homes, one hub & cloudkey

### ISSUE THREAD

**Issue by matellis** [hjdhjd/homebridge-unifi-protect2#33]
Thank you for version 3. Big update, very useful.

Is there any other way to handle multiple homes without having to setup multiple home bridges? It would be great to assign cameras to "homes" or have a way to add the same hub to multiple homes and then remove the cameras. The current implementation of disabling specific cameras can support this but only by maintaining multiple home bridge hubs.

Any thoughts on supporting multiple homes? It's a huge blind spot in most IoT implementations right now. Lutron only recently got round to supporting it even.

**Comment by hjdhjd** [comment]
@matellis Thanks for the compliment. It's a labor of love. :smile:

What's your definition of "homes" here? If you mean multiple HomeKit homes, the answer is that each HomeKit home needs to add the Homebridge bridge to make any Homebridge-attached plugins work. Since HomeKit doesn't allow any accessory (or bridge) to be added to more than one home simultaneously, you will need to launch a second instance of Homebridge to make it available to your second home.

It's not really a plugin problem...HomeKit is designed (rightly, in my mind) to have a unique coupling between an accessory and a HomeKit home.

It's not hard to launch a second Homebridge instance, on the same server no less. You just specify a different port for it in the config.json (and of course different working directories so you don't corrupt the other instance).

Hope this helps.

**Comment by matellis** [comment]
Understood, didn't think it would be so easy to do two home bridge instances on one controller. Thank you.

**Comment by hjdhjd** [comment]
No worries. If you're command-line savvy (and just being here is indication of that!) it's pretty easy. Lots of examples online too if you google around, I'm sure. Good luck!
