### ISSUE TITLE
Favorites for Camera on/off Affects Camera itself

### ISSUE THREAD

**Issue by matellis** [hjdhjd/homebridge-unifi-protect2#36]
When I select in Homekit "show as separate tiles", putting the "camera control" switch as a favorite or removing it make the camera itself also change. I would like the cameras to be in Favorites but not the "on/off" button. I can do this with my Nest integration (via Starling) but not on this. I can disable the on/off switches inside Homebridge for now, but not sure if this is intended implementation.

**Comment by hjdhjd** [comment]
This is not a plugin issue. This is HomeKit-intended behavior. When an accessory has multiple, associated services, HomeKit shows them as a single accessory starting in iOS 13.

Adrian's chosen to implement non-native switches (such as the occupancy switch in his plugin, for instance) as their own accessories instead of directly associating them with an existing accessory. Some accessories in the Nest plugin, like the Thermostat or Nest Protect ones, do have associated services attached to them, which you can also see in the same way you described above, and behave the same as you've described.

Philosophically, the intent in HomeKit is that if an accessory has multiple services, they should all be linked to that accessory. My design choices honor that intent. Aaron's do as well...he sees things like occupancy sensors as completely separate accessories, and arguably they are.

Net-net: it's not a bug. This is intended behavior. I have no plans to disassociate switches and sensors from the camera accessories they're attached to.

With that out of the way, generally speaking, I wouldn't do what you're trying to do. The motion switches are there as a convenience, but truly, they're there for automation events. Turn on motion detection when I leave the house, for example. I'd consider what you're really trying to do here, and act accordingly.

In my situation...I've got the better part of two dozen cameras. That would be a lot of switches on a home screen. :smile:

One other thing you could do is implement the liveviews feature. This will help you get to a "single switch to rule them all", if you so desire. Read more here: https://github.com/hjdhjd/homebridge-unifi-protect2/blob/master/docs/Liveviews.md

If you don't like the way the Home app UI works, you can use a different HomeKit app, like Eve and others.

Read more here: https://www.imore.com/how-ungroup-homekit-accessories-home-app and https://9to5mac.com/2019/08/20/homekit-ios-13/

**Comment by matellis** [comment]
All understood and healthy. The outcome is if you have a bunch of cameras in your favorites and you want motion sensors & enable switches, well you have two of those on your favorites page as well. It all gets a bit cluttered. I've put them at the bottom out of the way. Thanks
