### ISSUE TITLE
add HMCameraControl

### ISSUE THREAD

**Issue by justme-1968** [hjdhjd/homebridge-unifi-protect2#763]
**Is your feature request related to a problem? Please describe:**
no. it is a suggestion to expose more of the camera features through standard homekit characteristics

**Describe the solution you'd like:**
if possible please implement services that are exposed in homekit by the HMCameraControl class and the settingsControl member of the HMCameraProfile. HMCameraAudioControl, HMCameraStreamControl and HMCameraSnapshotControl are already there and it looks like HMCameraControl is the only one missing.

details can be found here: https://developer.apple.com/documentation/homekit/hmcamerasettingscontrol

**Describe alternatives you've considered:**
if this is not appropriate without a backend in the general homebridge/hab/hsv then i will open a suggestion there

**Comment by justme-1968** [comment]
please have a look here: https://github.com/homebridge/HAP-NodeJS/issues/960

it looks like the features are already exposed from HAP-NodeJS

or is still something missing ?

**Comment by hjdhjd** [comment]
Perhaps I should clarify further: there’s work that needs to be done **by Apple** in the Home app and in HomeKit.

The Home app doesn’t expose all these capabilities currently…it exposes a couple (namely status light and night light) and nothing else, to my knowledge (would welcome someone sharing screenshots showing otherwise because that means progress for the ecosystem!). 

Additionally, these capabilities aren’t exposed correctly within the HomeKit API itself. e.g.: https://github.com/homebridge/HAP-NodeJS/issues/934

There also needs to be work done on the HAP-NodeJS end, because it seems that while we (developers of Homebridge/HAP-NodeJS/HBUP) believe we’ve got it right (relative to the spec), clearly things don’t work as we would expect.

All that said…I view all this as minor capabilities that I won’t be addressing in the immediate future until I feel comfortable all of the above is addressed…and until Apple matures these edge capabilities, which given they’ve persisted for a number of years now I suspect won’t be a priority for them, they are unlikely to be meaningfully supported.

**Comment by justme-1968** [comment]
ok. i forgott to mention it is not about the home app. i'm current working on a homekit browser for the mac that displays everything that is available from the homekit api and will allow to integrate every homekit device into existing home automation systems.

the only cameras i currently have are 2 integrated with homebridge camera ffmpeg and 4 integrated with homebridge unifi protect. there i noticed that i can see the streamcontrol, snapshotcontrol and microphonecontrol, can display them and mostly use/switch them. but i noticed that cameracontrol is completely missing i.e. var settingsControl: HMCameraSettingsControl? from all bridged camera profiles is nil.

i think home will probably never expose all features of all devices. others like eve expose more and there will be apps that can work with everything. of course this is a little bit a chicken and egg problem. if no one is exposing some features then no-one will use them and especially for the integration with existing home automation systems exposing the controls from cameracontrol would be a big win. as things like moving the camera or zooming would be possible.

**Comment by hjdhjd** [comment]
As I mentioned above - **these capabilities do not work correctly in HomeKit**. It's not just the Home app. The Home app is often a proxy for Apple's priorities.

I won't be prioritizing these capabilities until those issues are resolved. I view these as largely vanity features - they cannot be automated in HomeKit and at-best provide a subpar experience to the native apps and web interface to tailor them.

Take night vision for instance. There are only two states available in HomeKit, but three states available in Protect. There isn't a good way to implement them without making a bunch of compromises or ugly workarounds.

I wish you well on your efforts and look forward to seeing your work. These capabilities have been largely in unimplemented by most folks because they can't be implemented without a lot of unacceptable compromises and there's so much more to do in other areas where we can make a functional difference rather than an esthetic one. 😀

**Comment by justme-1968** [comment]
ok. as i have no camera with a native integration i can not compare.

but a point to wonder: as all the characteristics in cameracontrol are generic HMCharacteristic i think there is nothing preventing a integration or a bridged accessory to use the available generic mechanisms like the metadata member to use more than two states. 

as my current implementation and also the homebridge plugin for fhem than i have developed are generic and can work with whatever is configured i would have no problem with more flexible characteristics.

but you are right, the camera support in my app is just a small part and as long as there are other open points i can't linger too long :)
